# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_DVB_HISTB_DMX) += histb-dmx.o
obj-$(CONFIG_VIDEO_HISTB_JPGE) += histb-jpge.o
obj-$(CONFIG_VIDEO_HISTB_VDEC) += histb-vdec.o
obj-$(CONFIG_VIDEO_HISTB_VENC) += histb-venc.o
obj-$(CONFIG_VIDEO_HISTB_VPSS) += histb-vpss.o

histb-vdec-y := histb-vdec-core.o histb-vdec-mpeg4.o histb-vdec-vc1.o
histb-venc-y := histb-venc-core.o histb-venc-rc.o
